package main

import "fmt"

func main() {
	fmt.Println("Hello from riyad")

	// hello_world()
	// static_type()
	// variables()
	// short_variables()
	// multiple_variable()
	// variable_convert()
	// const_variable()
	// string_formatter()
	// conditions()
	// functions()
	// short_function_params()
	// multiple_return()
	// name_return()
	// struct_test()
	// nested_struct()
	// anonyms_struct()
	// embedded_struct()
	// struct_method()
	// interface_test()
	// multiple_interface()
	// type_assertion()
	// type_switch()
	// error_test()
	// loops()
	// array_test()
	// slice_test()
	// variadic_spread()
	// slice_2d()
	// range_test()
	// map_test()
	// higher_order_function()
	// currying_test()
	// defer_test()
	// closures_test()
	// pointer_test()
	go_routine()

}
